package com.wu1g.service;

import com.wu1g.api.IDemoService;
import com.wu1g.dao.IDemoDao;
import com.wu1g.domain.Demo;
import com.wu1g.framework.annotation.RfAccount2Bean;
import com.wu1g.framework.service.BaseService;
import com.wu1g.framework.util.CommonConstant;
import com.github.pagehelper.PageHelper;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Isolation;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

@Service
@Slf4j
public class DemoService extends BaseService implements IDemoService {
    @Autowired
    private IDemoDao demoDao;

    @Override
    @Transactional(propagation = Propagation.REQUIRED, isolation = Isolation.DEFAULT, timeout = CommonConstant.DB_DEFAULT_TIMEOUT, rollbackFor = {Exception.class, RuntimeException.class})
    public String saveOrUpdateData(Demo dto) throws Exception {
        String msg = "seccuss";
        if (dto != null) {
            try {
                //判断数据是否存在
                if (dto.getId() != null && demoDao.isDataYN(dto) != 0) {
                    //数据存在
                    demoDao.updateByPrimaryKeySelective(dto);
                } else {
                    //新增
                    demoDao.insert(dto);
                }
            } catch (Exception e) {
                log.error("信息保存失败!", e);
                throw new Exception("信息保存失败!");
            }
        }
        return msg;
    }

    @Override
    public String deleteData(Demo dto) throws Exception {
        String msg = "seccuss";
        if (dto != null) {
            try {
                if(demoDao.deleteByPrimaryKey(dto)==0){
					throw new RuntimeException("数据不存在!");
                }
            } catch (Exception e) {
                log.error("物理删除失败!", e);
                throw new Exception(e.getMessage());
            }
        }
        return msg;
    }

    @Override
    @Transactional(propagation = Propagation.REQUIRED, isolation = Isolation.DEFAULT, timeout = CommonConstant.DB_DEFAULT_TIMEOUT, rollbackFor = {Exception.class, RuntimeException.class})
    public String deleteDataById(Demo dto) throws Exception {
        String msg = "seccuss";
        if (dto != null) {
            try {
                if(demoDao.deleteById(dto)==0){
					throw new RuntimeException("数据不存在!");
                }
            } catch (Exception e) {
                log.error("逻辑删除失败!", e);
                throw new Exception(e.getMessage());
            }
        }
        return msg;
    }

    @Override
    public List<Demo> findDataIsPage(Demo dto) throws Exception {
        List<Demo> dtos = null;
        try {
            PageHelper.startPage(PN(dto.getPageNum()), PS(dto.getPageSize()));
            dtos = (List<Demo>) demoDao.findDataIsPage(dto);
        } catch (Exception e) {
            log.error("信息查询失败!", e);
            throw new Exception("信息查询失败!");
        }
        return dtos;
    }

    @Override
    public List<Demo> findDataIsList(Demo dto) throws Exception {
        List<Demo> dtos = null;
        try {
            dtos = (List<Demo>) demoDao.findDataIsList(dto);
        } catch (Exception e) {
            log.error("信息查询失败!", e);
            throw new Exception("信息查询失败!");
        }
        return dtos;
    }

    @Override
    @RfAccount2Bean
    public Demo findDataById(Demo dto) throws Exception {
        Demo dto1 = null;
        try {
            dto1 = (Demo) demoDao.selectByPrimaryKey(dto);
        } catch (Exception e) {
            log.error("信息查询失败!", e);
            throw new Exception("信息查询失败!");
        }
        return dto1;
    }

    @Override
    public String recoveryDataById(Demo dto) throws Exception {
        String msg = "seccuss";
        if (dto != null) {
            try {
                if(demoDao.recoveryDataById(dto)==0){
					throw new RuntimeException("数据不存在!");
                }
            } catch (Exception e) {
                log.error("数据恢复失败!", e);
                throw new Exception(e.getMessage());
            }
        }
        return msg;
    }
}